import mongoose from "mongoose";
const hotelSchema =new mongoose.Schema({
    hotelname:{
        type:String,
        required:true,
    },
    name:{
        type:String,
        required:true
    },
    number:{
        type:Number,
        required:true
    },
   fromdate:{
        type:Date,
        required:true
    },
    todate:{
        type:Date,
        required:true
    },
    rooms:{
        type:Number,
        default:1
    },
    persons:{
        type:Number,
        default:1
    }
},
{
    timestamps:true
})